### ISSUE TITLE
Modify Perma Join to support multi field keys

### ISSUE THREAD

**Issue by strattonma** [pbsag/gisdk_tools#39]
Perma Join could make use of JoinViewMulti in order to allow joining using more than 1 field.  Example: 

        // join pnr bin files to trips bin file
        f1 = OpenTable("trips", "FFB", {scen_dir + "/Output/mc/trips.bin", })
        f2 = OpenTable("pnr", "FFB", {scen_dir + "/Output/mc/pnr.bin", })
        jv = JoinViewsMulti("perma jv", {"trips.node_id", "trips.[node_id:1]"}, {"pnr.RCIndex", "pnr.[RCIndex:1]"}, )
        SetView(jv)
        tempBIN = scen_dir + "/Output/mc/trips_out.bin"
        tempDCB = scen_dir + "/Output/mc/trips_out.DCB"
        ExportView(jv + "|", "FFB", tempBIN, , )
        CloseView(jv)
        CloseView(f1)
        CloseView(f2)

**Comment by dkyleward** [comment]
Just checking - is this a 'nice to have' or needed soon?

**Comment by strattonma** [comment]
Nice to have

**Comment by dkyleward** [comment]
Hey Matt,

I took another look at your example code. `Perma Join` isn't actually intended for that purpose - only for joining tables to geographic files like link or zone layers, in which case every row has a unique ID and `JoinViewsMulti()` isn't needed.

What you actually want to use is either `JoinViewsMulti()` directly or gplyr. Here is how gplyr would look:

```
df1 = CreateObject("df", scen_dir + "/Output/mc/trips.bin")
df2 = CreateObject("df", scen_dir + "/Output/mc/pnr.bin")
df1.left_join(df2, {"node_id", "node_id:1"}, {"RCIndex", "RCIndex:1"})
tempBIN = scen_dir + "/Output/mc/trips_out.bin"
df1.write_bin(tempBIN)
```

Note that only the latest version of GT supports that method of data frame construction. For previous versions, you would use:

```
df1 = CreateObject("df")
df1.read_bin(scen_dir + "/Output/mc/trips.bin")
```

I'm going to check if Caliper has fixed their own JoinTableToLayer() macro. If not, I will rename "Perma Join" to "Join Table to Layer" to avoid confusion.

**Comment by strattonma** [comment]
Thanks for clarifying.
